Defect#241 : Fixing issue about HPCloud account used
Change-Id: I817f4050c276ef9f2d0e6d43876c6282240c0542

diff --git a/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl b/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
--- a/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
+++ b/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
@@ -68,12 +68,7 @@ fi
 
 # Defines which HPCloud account to use.
 
-# if FORJ_HPC account name doesn't exist, build.sh will create a copy of 'hp' account (hpcloud account hp)
-# Then all 'hp' account settings used to access services are copied and used as default.
-# If you need to change and ensure some settings, different than default, uncomment any required HPC* variables.
-FORJ_HPC=$GITBRANCH-maestro-build-13.05
-# If this account doesn't exist, build.sh will create it from hp account.
-
+# build.sh requires 'FORJ_HPC' to exist. forj cli will sent this variable to build.sh
 
 # HPCloud services settings used to create Maestro:
 # Uncomment to ensure setting you need.
@@ -125,6 +120,13 @@ SET_DOMAIN="{SET_DOMAIN!}"
 # FORJ_HPC_NOVA_KEYPUB=~/.hpcloud/keypairs/nova.pub
 
 # forj cli defines the following variables
+if [ "$FORJ_HPC" = "" ]
+then
+   echo "build env error: forj cli did not set FORJ_HPC. Cannot go on. check forj setup."
+   exit 1
+fi
+Info "forj-cli - FORJ_HPC = $FORJ_HPC"
+
 if [ "$FORJ_HPC_NET" = "" ]
 then
    echo "build env error: forj cli did not set FORJ_HPC_NET. Cannot go on. check forj setup."
@@ -279,7 +281,7 @@ fi
 
 if [ "${META[hpcloud_priv]}" = "" ]
 then # On this configuration set from infra, we use the infra bootstrap to complete the maestro one.
-   G64FILE=~/.cache/forj/${GITBRANCH}.forj-13.5.g64
+   G64FILE=~/.cache/forj/${FORJ_HPC}.g64
    if [ ! -f $G64FILE ]
    then
       echo "Missing hpcloud_priv meta or file '$G64FILE' not found. You need one or the other."
