Fixing interaction between build.sh and forj cli
Change-Id: I3f73aed97d35dce1cb8a2e87bfe495000076ce61

diff --git a/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl b/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
--- a/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
+++ b/templates/infra/hpcloud-maestro.box.GITBRANCH.env.tmpl
@@ -59,8 +59,6 @@ fi
 # - APPPATH                 : Path to bootstrap files to use.
 # 
 
-# Internal Forj public key used.
-FORJ_HPC_NOVA_KEYPUB=~/.hpcloud/keypairs/nova-USWest-AZ3.pub
 
 ################################################
 # HPCloud Services settings section
@@ -116,22 +114,9 @@ SET_DNS_TENANTID="{SET_DNS_TENANTID!}"
 # SET_DNS_ZONE: Ex: region-a.geo-1
 SET_DNS_ZONE="{SET_DNS_ZONE!}"
 
-# SET_NET: HPCloud Network name to use for boot.
-SET_NET="{SET_NET!:private}"
-
-# SET_KEYPAIR: Define the key pair name to use. Default is 'nova'
-SET_KEYPAIR="{SET_KEYPAIR!:nova}"
-
-# SET_SECURITY_GROUP: Security group used to open access to some IP ports. 'default' is the default value. FORJ needs to open several ports. If possible, use a different security group for FORJ
-SET_SECURITY_GROUP="{SET_SECURITY_GROUP!:default}"
-
 # SET_DOMAIN: Domain used for DNS. Each server will be attached to a public IP. An 'A' record in the DNS service will need to be added to your HPCloud DOMAIN.
 # SET_DOMAIN: Ex: dev.forj.io
 SET_DOMAIN="{SET_DOMAIN!}"
-
-# FORJ_BASE_IMG: Image used to build Maestro. It must be an ubuntu 12.04 base image. if you had built proto2b, you can set it there.
-FORJ_BASE_IMG="{FORJ_BASE_IMG!:Ubuntu Precise 12.04.4 LTS Server 64-bit 20140414 (Rescue Image)}"
-# FORJ_BASE_IMG="proto2b" # proto2b is built from maestro/build. Read the README.md to create it.
 
 # ----------------------------------------
 
@@ -139,21 +124,41 @@ FORJ_BASE_IMG="{FORJ_BASE_IMG!:Ubuntu Precise 12.04.4 LTS Server 64-bit 20140414
 # Required! Uncomment it and update it. This is your HPCloud public key used. Build.sh will add this key in the hpcloud boot call.
 # FORJ_HPC_NOVA_KEYPUB=~/.hpcloud/keypairs/nova.pub
 
-
+# forj cli defines the following variables
 if [ "$FORJ_HPC_NET" = "" ]
 then
-   FORJ_HPC_NET=${SET_NET} # Network required for Maestro to boot
+   echo "build env error: forj cli did not set FORJ_HPC_NET. Cannot go on. check forj setup."
+   exit 1
 fi
+Info "forj-cli - FORJ_HPC_NET = $FORJ_HPC_NET"
 
 if [ "$FORJ_KEYPAIR" = "" ]
 then
-   FORJ_KEYPAIR=${SET_KEYPAIR}
+   echo "build env error: forj cli did not set FORJ_KEYPAIR. Cannot go on. check forj setup."
 fi
+Info "forj-cli - FORJ_KEYPAIR = $FORJ_KEYPAIR"
 
 if [ "$FORJ_SECURITY_GROUP" = "" ]
 then
-   FORJ_SECURITY_GROUP=${SET_SECURITY_GROUP}
+   echo "build env error: forj cli did not set FORJ_SECURITY_GROUP. Cannot go on. check forj setup."
+   exit 1
 fi
+Info "forj-cli - FORJ_SECURITY_GROUP = $FORJ_SECURITY_GROUP"
+
+# Internal Forj public key used.
+if [ "$FORJ_HPC_NOVA_KEYPUB" = "" ]
+then
+   echo "build env error: forj cli did not set FORJ_HPC_NOVA_KEYPUB. Cannot go on. check forj setup."
+   exit 1
+fi
+Info "forj-cli - FORJ_HPC_NOVA_KEYPUB = $FORJ_HPC_NOVA_KEYPUB"
+
+if [ "$FORJ_BASE_IMG" = "" ]
+then
+   echo "build env error: forj cli did not set FORJ_BASE_IMG. Cannot go on. check forj setup."
+   exit 1
+fi
+Info "forj-cli - FORJ_BASE_IMG = $FORJ_BASE_IMG"
 
 
 # - FORJ_FLAVOR                    : HPCloud flavor ID to use for boot.
@@ -240,7 +245,7 @@ fi
 
 if [ "${META[network_name]}" = "" ]
 then
-   META[network_name]="network_name=$SET_NET" # Network required for boxes to boot.
+   META[network_name]="network_name=$FORJ_HPC_NET" # Network required for boxes to boot.
 fi
 
 if [ "${META[bootstrap]}" = "" ]
